### ISSUE TITLE
All Attributes: delete empty items at database

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1005]
## Checklist:

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue
## My environment is:

| Key | Value | Comments |
| --- | --- | --- |
| PHP version: | 5.6 |  |
| Contao version: | 3.5.8 |  |
| MetaModels version: | 2.0.0 a10 |  |
| Installation via composer | yes |  |
| Installed MetaModels packages | bundle_all |  |
## Issue description

if you clear a existing complex/translated item e.g. attribute_translatedtext we have a empty item at database - see screenshot below

e.g. the same https://github.com/MetaModels/attribute_translatedurl/issues/4
## Steps to reproduce
1. multilanguage MM with translated text
2. fill at input mask and save
3. delete the text at input mask and save
4. look at database...
## Screenshots

![shot187](https://cloud.githubusercontent.com/assets/1045318/14343682/dd34f4a4-fca2-11e5-8fff-42ad2acd97d2.jpg)

## Check and update
- [x] attribute_tabletext (PR https://github.com/MetaModels/attribute_tabletext/pull/19)
- [x] attribute_url (PR https://github.com/MetaModels/attribute_url/pull/14)
- [x] attribute_translatedurl (PR https://github.com/MetaModels/attribute_translatedurl/pull/8)
- [x] attribute_tags
- [x] attribute_translatedalias
- [x] attribute_translatedcheckbox (PR https://github.com/MetaModels/core/pull/1117)
- [x] attribute_translatedcombinedvalues (PR https://github.com/MetaModels/core/pull/1117)
- [x] attribute_translatedfile (PR https://github.com/MetaModels/attribute_translatedfile/pull/15)
- [x] attribute_translatedlongtext (PR https://github.com/MetaModels/core/pull/1117)
- [x] attribute_translatedselect
- [x] attribute_translatedtabletext (PR https://github.com/MetaModels/attribute_translatedtabletext/pull/19)
- [x] attribute_translatedtags
- [x] attribute_translatedtext (PR https://github.com/MetaModels/core/pull/1117)

**Comment by johannes-bittner** [comment]
Soweit schon  einmal geprüft und nicht funktionierend: 
attribute_translatedtext => Eintrag bleibt stehen
attribute_translatedcheckbox => Eintrag bleibt stehen
attribute_translatedcombinedvalues => Eintrag bleibt stehen
attribute_translatedfile => Eintrag bleibt stehen
attribute_translatedlongtext => Eintrag bleibt stehen
attribute_translatedtabletext => Eintrag bleibt stehen

**Comment by johannes-bittner** [comment]
attribute_translatedtext => OK
attribute_translatedcheckbox => OK
attribute_translatedtabletext => OK
attribute_translatedlongtext => OK
attribute_translatedcombinedvalues => OK

**Comment by zonky2** [comment]
setTranslatedDataFor at https://github.com/MetaModels/core/blob/master/src/MetaModels/Attribute/TranslatedReference.php#L299 should implement at all attributes as own method

**Comment by zonky2** [comment]
with PR https://github.com/MetaModels/attribute_translatedfile/pull/15
attribute_translatedfile => OK

**Comment by johannes-bittner** [comment]
- [x] attribute_tabletext (PR MetaModels/attribute_tabletext#19)
- [x] attribute_url (PR MetaModels/attribute_url#14)
- [x] attribute_translatedurl (PR MetaModels/attribute_translatedurl#8)
- [x] attribute_tags
- [x] attribute_translatedalias
- [x] attribute_translatedcheckbox (PR #1117)
- [x] attribute_translatedcombinedvalues (PR #1117)
- [x] attribute_translatedfile (PR MetaModels/attribute_translatedfile#15)
- [x] attribute_translatedlongtext (PR #1117)
- [x] attribute_translatedtabletext (PR #1117)
- [x] attribute_translatedtags
- [x] attribute_translatedtext (PR #1117)

**Comment by zonky2** [comment]
@discordier || @stefanheimes pls merge the linked PRs

**Comment by baumannsven** [comment]
Merged in 76e62168d0d15cb3c25fd727445ef27f4c83f95a

**Comment by zonky2** [comment]
thx
