### ISSUE TITLE
Can't save tags field based on other meta model with custom sorting

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#1006]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | 5.6.11         |                                  |
| Contao version:                     |  3.4.5        |                                  |
| MetaModels version:                 |   dev-master 0b68f4a)       | The problem was also reproducible with dev-master 93433a4, but I got additional errors there (that is why I did not upgrade https://github.com/contao-community-alliance/dc-general/issues/222) |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       | bundle_all |                                  |

## Issue description

I can't save a tags value where the values are sorted by the "sorting" field.

## Steps to reproduce

1. Create metamodel "standorte", add some cities, use backend sorting
2. Create metamodel "landingpages
" which use standorte as a tag input field, tag sorting = "sorting"
3. Edit standorte
4. choose some of the tags,
5. Save

This is the config of the Field "standorte" in "landingpages"

![metamodel-config-landingpages-and-workaround](https://cloud.githubusercontent.com/assets/1087128/14456802/0a5719fa-00a7-11e6-88ad-467ab578f641.png)

## Describe the behaviour of the application

I get an error 
![fehler-beim-speichern-redacted](https://cloud.githubusercontent.com/assets/1087128/14456764/db71fd6c-00a6-11e6-9747-9dfbb578f545.png)

A workaround would be, to set the "Tag sorting" to the field "id" (see above)

## Describe the expected behaviour of the application

It should save

## Screenshots

I did some debugging: It looks like the expected and actual value of the array just differ in sorting

![debugging-exception-sortierung](https://cloud.githubusercontent.com/assets/1087128/14456825/2e18a354-00a7-11e6-9a32-cfc8e732b76c.png)

**Comment by zonky2** [comment]
Hi @amenk, its possible to update your enviroment? 

You should use the LTS-Version of Contao - look at http://metamodels.readthedocs.org/de/latest/manual/install.html#metamodels-installieren-und-aktualisieren and the latest MM (Core 2.0.0 a10) with DCG (2.0.0 b34)

**Comment by amenk** [comment]
While I understand this advice, would you say it is fixed an up to date environment?
Currently we use sorting by ID as a workaround, so I don't get more time from the PM.
Just want to make sure that it's fixed in future versions...

**Comment by zonky2** [comment]
> While I understand this advice, would you say it is fixed an up to date environment?

... may be ;-) its possible to try it?

we had a small update to sort the checkboxes - https://github.com/MetaModels/core/pull/951

**Comment by amenk** [comment]
Not fully convinced that is fixed there. No time to try at the moment. If you are convinced that it is fixed, you are free to close :) Otherwise I will try it one day on a recent Contao + MM version.

**Comment by zonky2** [comment]
I´m not sure -  MM lives by the help of all.. everybody have "no time" ;-)

**Comment by amenk** [comment]
Sure ... usually I always have time for FOSS, even the manager does not like it sometimes ;-)
Is there by chance a public demo installation of the recent MM with backend access where I could try to reproduce?

**Comment by zonky2** [comment]
if you have a test case of MM, you can send me the login data - e.g. as PM at community forum

**Comment by amenk** [comment]
I currently don't - as I do not run a system with the recent version... Would have to set this up first.

**Comment by zonky2** [comment]
Check with
C 3.5.12
MM a11
DCG b36

* two MM "Mitarbeiter" with relation to "Abteilung"
* Abteilung as tags

Abteilung: Standard sorting as input
![shot235](https://cloud.githubusercontent.com/assets/1045318/15956313/f9a5c1a0-2ee7-11e6-9b55-dfc0b5fbbeca.jpg)

Abteilung: after manual sorting
![shot236](https://cloud.githubusercontent.com/assets/1045318/15956320/0e9178d4-2ee8-11e6-9eba-ad61f2dbab9e.jpg)

Mitarbeiter: choose Abteilung (you can see the own sorting)
![shot237](https://cloud.githubusercontent.com/assets/1045318/15956335/38151ce2-2ee8-11e6-8d62-c696d8e7fc43.jpg)

Mitarbeiter: BE listing
![shot238](https://cloud.githubusercontent.com/assets/1045318/15956345/458e7634-2ee8-11e6-8ac9-330c1f7ff484.jpg)

=> works fine in my mind...

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@amenk could you please have a final look at this and tell if your issue has been resolved?
