### ISSUE TITLE
Finalize 2.0.0

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1060]
# TODO
- [x] Bump PHP and Contao version (see MetaModels/core#1011)
- [x] Add `.github/` templates - see [example](https://github.com/MetaModels/core/tree/e672fc555c7341059d76625cf0b5853b35c69070/.github) but ensure to update the links in the files!
- [x] Add `.gittattributes` file (see MetaModels/core#846)
- [x] remove `minimum-stability` from `composer.json` and add 
`"metamodels/core": "~2.0@alpha"` and 
`"contao-community-alliance/dc-general": "~2.0@beta"` and
`"license": "LGPL-3.0-or-later"`
- [x] Ensure `LICENSE` file is present!
- [x] Update badges in `README.md`!
- [x] Check build status is green!
- [x] Add `.check-author.yml` or check this
- [*] Check all file header => we check this when working on MM 2.1

**Comment by zonky2** [comment]
finished
