### ISSUE TITLE
Finalize 2.0.0 - Overview

### ISSUE THREAD

**Issue by zonky2** [MetaModels/core#1061]
# TODO for each repository:
Please use this template snipet:
```
- [ ] Bump PHP and Contao version (see MetaModels/core#1011)
- [ ] Fix all remaining tickets tagged for 2.0.0
- [ ] Check all file header (like https://github.com/MetaModels/core/blob/master/src/MetaModels/MetaModel.php#L1-L26)
- [ ] Add `.check-author.yml` or check this
- [ ] Add `.github/` templates - see [example](https://github.com/MetaModels/core/tree/e672fc555c7341059d76625cf0b5853b35c69070/.github) but ensure to update the links in the files!
- [ ] Add `.gittattributes` file (see MetaModels/core#846)
- [ ] remove `minimum-stability` from `composer.json` and add `"metamodels/core": "~2.0@alpha"` and `"contao-community-alliance/dc-general": "~2.0@beta"`
- [ ] Ensure `LICENSE` file is present! (see https://github.com/MetaModels/core/blob/master/LICENSE)
- [ ] Update badges in `README.md`! (look at first rows https://raw.githubusercontent.com/MetaModels/core/master/README.md)
- [ ] Check build status is green!
```
# List of repositories to apply above tasks to:
- [x] metamodels/attribute_alias - 2.0.0
- [x] metamodels/attribute_checkbox - 2.0.1
- [x] metamodels/attribute_combinedvalues - 2.0.0
- [x] metamodels/attribute_country - 2.0.0
- [x] metamodels/attribute_decimal - 2.0.0
- [x] metamodels/attribute_file - 2.0.0
- [x] MetaModels/attribute_geoprotection - 2.0.2
- [x] metamodels/attribute_langcode - 2.0.0
- [x] metamodels/attribute_longtext - 2.0.0
- [x] metamodels/attribute_numeric - 2.0.0
- [x] metamodels/attribute_rating - 2.0.0
- [x] metamodels/attribute_select - 2.0.0
- [x] metamodels/attribute_tabletext - 2.0.0
- [x] metamodels/attribute_tags - 2.0.0
- [x] metamodels/attribute_text - 2.0.0
- [x] metamodels/attribute_timestamp - 2.0.0
- [x] metamodels/attribute_translatedalias - 2.0.0
- [x] metamodels/attribute_translatedcheckbox - 2.0.0
- [x] metamodels/attribute_translatedcombinedvalues - 2.0.0
- [x] metamodels/attribute_translatedfile - 2.0.0
- [x] metamodels/attribute_translatedlongtext - 2.0.0
- [x] metamodels/attribute_translatedselect - 2.0.0
- [x] metamodels/attribute_translatedtabletext - 2.0.0
- [x] metamodels/attribute_translatedtags - 2.0.0
- [x] metamodels/attribute_translatedtext - 2.0.0
- [x] metamodels/attribute_translatedurl - 2.0.0
- [x] metamodels/attribute_url - 2.0.1
- [x] metamodels/bundle_all - 2.0.0
- [x] metamodels/bundle_attributes - 2.0.1
- [x] metamodels/bundle_filter - 2.0.0
- [x] metamodels/bundle_nontranslated - 2.0.1
- [x] metamodels/bundle_translated - 2.0.1
- [x] metamodels/core - 2.0.0-alpha14 - https://github.com/MetaModels/core/issues/1060
- [x] metamodels/filter_checkbox - 2.0.0
- [x] metamodels/filter_fromto - 2.0.0
- [x] MetaModels/filter_perimetersearch 2.0.0
- [x] metamodels/filter_range - 2.0.0
- [x] metamodels/filter_select - 2.0.0
- [x] metamodels/filter_tags - 2.0.0
- [x] metamodels/filter_text - 2.0.0

**Comment by zonky2** [comment]
MM-core is the last and only one...

**Comment by zonky2** [comment]
finished
