### ISSUE TITLE
Referenced Meta Models with brackets ( ... ) can not be chosen (Error: did not accept the value)

### ISSUE THREAD

**Issue by amenk** [MetaModels/core#1501]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available (dev)
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue%20did%20not%20accept%20the%20value

## My environment is:

(Please fill in the actual values from your environment - check Contao Manager or use `composer show`)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     8.1       |                                |
| Contao version:                     |   4.13       |                                  |
| MetaModels version:                 |         2.3@dev     |                              |
| Installed MetaModels packages:      |  almost all        |                                  |
| DCG version:                        |     2.3@dev     |                                  |

## Issue description

When selecting a metamodel reference which contains `( )` in the field name, it is not accepted.

## Steps to reproduce

1. Have to metamodels, one (A) references to another (B)
2. in B create an entry with the Name "Frankfurt (Oder)"
3. Reference field is the name
4. Choose the new entry in A

## Describe the behaviour of the application

Message:

```
Ungültige Auswahl!
Property vita_location (select) did not accept the value (The values differ. Encountered type NULL expected string (Found NULL, expected 'Frankfurt (Oder)')).
```
## Describe the expected behaviour of the application

The form can be saved

## Workaround

Rename the entry to "Frankfurt - Oder" and chose it.

Also it might be possible to use the id field as reference instead of the name, but I guess we would need to migrate the references then?

## Screenshots

![image](https://github.com/MetaModels/core/assets/1087128/c40f2041-0a60-4966-97a6-82f608763c5f)
![image](https://github.com/MetaModels/core/assets/1087128/9177fadd-4ee2-4338-82b2-969ad403d459)

## Context

We have this in a Migration project from Countao 4.3 with an older Metamodels version. The data was copied to the new instance - so this might have worked in the older version of Contao / Metamodels.

**Comment by zonky2** [comment]
@amenk Could you check the DB to see how "Frankfurt (Oder)" was saved - as entered or encoded?

**Comment by amenk** [comment]
1) It's saved in encoded form `Frankfurt &#40;Oder&#41;`
2) Yes it's a MM table -- my first thought was to select the alias or ID as well. But wouldn't we need to migrate the existing relations or does this happen automatically?
3) Nothing seems to be multilinguage

**Comment by amenk** [comment]
Re 2) If I select "id" as the alias column (we don't have an alias) that would work, yes

**Comment by zonky2** [comment]
You should **always** create an alias for relations - e.g. to have clean URL parameters for filtering.

I assume that the problem is with the encoding - I'll have to create a test case.

You can check this to change `Frankfurt &#40;Oder&#41;` to `Frankfurt (Oder)` directly in DB

**Comment by amenk** [comment]
okay, good to know - while I think we don't have filters on this field anyways.

When changing it in the database it does not help - same error.
Also in the Backend Form it selects the first entry after we get the error.

**Comment by zonky2** [comment]
hmm... o.k. - I can can check this after create a test case....

**Comment by zonky2** [comment]
The problem is that Contao automatically changes the text when saving it to the database - so `Frankfurt (Oder)` becomes `Frankfurt &#40;Oder&#41;`

The conversion can be switched off in the settings of the attribute of the input mask, so that `Frankfurt (Oder)` is saved in the DB.

In MM B, however, we cannot determine which setting was selected for MM A in the input mask or whether there were other conversions.

As written, an alias attribute should also be selected for Alias...

In MM we can't solve the problem - in the future the conversion before storing in the DB from Contao will be omitted - we welcome this very much and hope the "feature" will come in Contao 5

**Comment by amenk** [comment]
> The conversion can be switched off in the settings of the attribute of the input mask, so that Frankfurt (Oder) is saved 
> in the DB.

I tried to find such a setting in `table=tl_metamodel_dcasetting&id=tl_metamodel_dcasetting` of MM A.

![image](https://github.com/MetaModels/core/assets/1087128/1f095a16-7692-49ba-b4df-4a8947ab8b66)

But I guess, there just is no other solution than creating an alias for now? I think I misunderstood the answer first :-)
I think we will just create an alias.

**Comment by amenk** [comment]
> save your item with name Frankfurt (Oder) and check the value at DB

Perfect, works :-)
