### ISSUE TITLE
Change to c-c-a code style and utilize ccabs.

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#602]
Core:
- [X] https://github.com/MetaModels/core

Attributes:
- [x] https://github.com/MetaModels/attribute_alias
- [X] https://github.com/MetaModels/attribute_checkbox
- [X] https://github.com/MetaModels/attribute_color (Thanks to @cliffparnitzky MetaModels/attribute_color#2)
- [X] https://github.com/MetaModels/attribute_combinedvalues (Thanks to @bytehead MetaModels/attribute_combinedvalues#8)
- [X] https://github.com/MetaModels/attribute_country (Thanks to @cliffparnitzky MetaModels/attribute_country#7 & MetaModels/attribute_country#9)
- [X] https://github.com/MetaModels/attribute_decimal (Thanks to @cliffparnitzky, MetaModels/attribute_decimal#5)
- [X] https://github.com/MetaModels/attribute_file (Thanks to @bytehead MetaModels/attribute_file#37)
- [x] https://github.com/MetaModels/attribute_geoprotection (Thanks to @bytehead )
- [X] https://github.com/MetaModels/attribute_langcode (Thanks to @cliffparnitzky MetaModels/attribute_langcode#4)
- [X] https://github.com/MetaModels/attribute_longtext (Thanks to @cboelter MetaModels/attribute_longtext#10)
- [X] https://github.com/MetaModels/attribute_numeric (Thanks to @bytehead MetaModels/attribute_numeric#4)
- [X] https://github.com/MetaModels/attribute_rating (Thanks to @bytehead ) https://github.com/MetaModels/attribute_rating#12)
- [X] https://github.com/MetaModels/attribute_select
- [x] https://github.com/MetaModels/attribute_tabletext (Tanks to @bytehead )
- [X] https://github.com/MetaModels/attribute_tags (Thanks to @cboelter MetaModels/attribute_tags#27)
- [X] https://github.com/MetaModels/attribute_text (Thanks to @cboelter MetaModels/attribute_text#6)
- [X] https://github.com/MetaModels/attribute_timestamp (Thanks to @bytehead, @cboelter MetaModels/attribute_timestamp#15)
- [X] https://github.com/MetaModels/attribute_translatedalias
- [X] https://github.com/MetaModels/attribute_translatedcheckbox (WIP by @cboelter)
- [X] https://github.com/MetaModels/attribute_translatedcombinedvalues (Thanks to @bytehead MetaModels/attribute_translatedcombinedvalues#2)
- [X] https://github.com/MetaModels/attribute_translatedfile (Thanks to @bytehead MetaModels/attribute_translatedfile#7)
- [X] https://github.com/MetaModels/attribute_translatedlongtext (Thanks to @cboelter MetaModels/attribute_translatedlongtext#4)
- [X] https://github.com/MetaModels/attribute_translatedselect
- [X] https://github.com/MetaModels/attribute_translatedtabletext (Thanks to @bytehead MetaModels/attribute_translatedtabletext#6)
- [X] https://github.com/MetaModels/attribute_translatedtags
- [X] https://github.com/MetaModels/attribute_translatedtext (Thanks to @cboelter MetaModels/attribute_translatedtext#4)
- [X] https://github.com/MetaModels/attribute_translatedurl (Thanks to @cboelter MetaModels/attribute_translatedurl#1)
- [X] https://github.com/MetaModels/attribute_url (Thanks to @cboelter MetaModels/attribute_url#11)

Filter:
- [X] https://github.com/MetaModels/filter_checkbox (Thanks to @dmolineus MetaModels/filter_checkbox#4)
- [X] https://github.com/MetaModels/filter_fromto (Thanks to @dmolineus MetaModels/filter_fromto#7)
- [x] https://github.com/MetaModels/filter_perimetersearch
- [X] https://github.com/MetaModels/filter_range
- [X] https://github.com/MetaModels/filter_register
- [X] https://github.com/MetaModels/filter_select (Thanks to @dmolineus MetaModels/filter_select#8)
- [x] https://github.com/MetaModels/filter_tags (Thanks to @dmolineus MetaModels/filter_tags#10)
- [x] https://github.com/MetaModels/filter_text (Thanks to @dmolineus MetaModels/filter_text#9)
