### ISSUE TITLE
[Roadmap 2.0.0]

### ISSUE THREAD

**Issue by tim-bec** [MetaModels/core#624]
Wir haben Eure Rückmeldungen hier, im IRC und im [Forum](https://community.contao.org/de/showthread.php?53371-Was-ist-mit-metaModels-los) gehört und uns einen Schlachtplan zurechtgelegt.
Gestartet sind wir mit einem Ticket-Marathon von 10 Stunden. Alle Tickets die dem [Milestone 2.0.0]( https://github.com/MetaModels/core/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0) zugeordnet sind müssen nun noch abgearbeitet werden. 

Weiter unten haben wir die größten Baustellen etwas übersichtlicher zusammengefasst. Über fleißige HelferInnen mit Tests, Pull-Request und Spenden freuen wir uns natürlich sehr :-)

# Allgemeines

Neben der großen Aufgabe "2.0 stable", werden wir in den kommenden Wochen auch die Bezeichnungen der Versionen und Hinweise dazu in den diversen Quellen verständlicher gestalten.

* MetaModels 2.0 (Alias: TNG) - Unser aktuelles Ziel
* MetaModels 1.0.x + 1.1.x - beides die "alten" Versionen für Contao 2 und Contao 3 die wir aktuell aus Zeitmangel nicht mehr pflegen - diese Versionen werden bald ins Archiv verschwinden.

# Roadmap MetaModels 2.0

Wir konzentrieren uns aktuell auf Fehlerbeseitigung und finale Implementierung der im Milestone festgelegten Features. Dieser Stand kann dann (endlich) mittels eines Tags, wie von anderen Erweiterungen oder dem Contao-Core bekannt, festgezurrt, haben aber dennoch versucht einen groben Zeitrahmen zu definieren. Einen "Sprint" setzen wir aktuell mit zwei Wochen an, wenn alles glatt läuft, gibt es MetaModels 2.0 also in 2 Monaten, mit folgenden Features:

## Features
- [x] Mehrsprachigkeit (BE / FE)
- [x] Varianten (BE / FE)
- [x] Flache Abbildungen (BE / FE)
- [x] Hierachie Abbildungen (BE)
- [x] Sortierung (BE)
- [x] Filter (BE / FE)
- [x] Gruppierung (BE)
- [x] Kopieren und duplizieren (BE)
- [X] Anzeigebedingungen (Erweiterte "Subpaletten") (BE)

## Sprint 1
- [x] [C-C-A CodeStyle](https://github.com/MetaModels/core/issues/602)
- [X] [Rework Factories](https://github.com/MetaModels/core/issues/606)
- [X] [Rework Factories Filters](https://github.com/MetaModels/core/issues/698)
- [X] [Alias Generierung](https://github.com/MetaModels/core/issues/607)
- [X] Registrierung der MetaModels Einträge in den [Contao Suchindex] (https://github.com/MetaModels/core/issues/128#issuecomment-60149441)

## Sprint 2
~~Wir arbeiten aktuell im Branch [rework-sorting](https://github.com/MetaModels/core/tree/rework-sorting) die Sortierungs und Gruppierungsfunktion neu aus.~~ Arbeiten wurden abgeschlossen.

### sortieren (Drag & Drop)
- [x] https://github.com/contao-community-alliance/dc-general/issues/73
- [x] https://github.com/contao-community-alliance/dc-general/issues/72
- [x] https://github.com/contao-community-alliance/dc-general/issues/13
- [x] https://github.com/contao-community-alliance/dc-general/issues/56 
- [x] https://github.com/contao-community-alliance/dc-general/issues/38
- [x] https://github.com/contao-community-alliance/dc-general/issues/37

### Gruppieren
- [X] https://github.com/contao-community-alliance/dc-general/issues/71

### Filter
- [ ] https://github.com/MetaModels/core/issues/312
- [X] https://github.com/MetaModels/core/issues/496
- [X] https://github.com/MetaModels/core/issues/144
- [x] https://github.com/MetaModels/core/issues/477
- [X] https://github.com/contao-community-alliance/dc-general/issues/70
- [x] https://github.com/contao-community-alliance/dc-general/issues/83

## Sprint 3

- [x] [Template-Auswahl] (https://github.com/MetaModels/core/issues/321) + https://github.com/MetaModels/core/issues/579
- [X] Kopieren / duplizieren von Einträgen [DC-General](https://github.com/contao-community-alliance/dc-general) + contao-community-alliance/dc-general#83
- [x] https://github.com/MetaModels/core/issues/184
- [ ] Restliche [DC-General](https://github.com/contao-community-alliance/dc-general/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0)

## Sprint 4
- [X] Anwenden von Bedingungen auf Legenden (#828)
- [x] Darstellungsfehler, CSS Anpassungen
- [ ] Letzte Fehlerkorrekturen

# Wie könnt ihr helfen?

* ~~Pull-Requests Codingstyle https://github.com/MetaModels/core/issues/602~~
* ~~Pull-Requests Eventdispatcher https://github.com/MetaModels/core/issues/601~~
* Aktuelle Entwicklungsstände testen und Fehler als Ticket melden.

# Wie sieht ein ordentliches Ticket aus?

* Genaue Beschreibung eurer Umgebung (Contao Version, MM Version, DCG Version usw. am besten direkt aus Composer).
* Genaue Fehlerbeschreibung, möglichst inkl. komplettem Stack trace, Einträgen in System/Log und error.log"f
* Genaue Beschreibung wie sich das Problem reproduzieren lässt
* Bei extremen Sachen ggf. Installation bzw. Zugangsdaten an uns per Mail

# Ausblick

## MetaModels 1.0.x 1.1.x

Wir haben uns entschlossen, den Support für die Versionen 1.1.x und 1.0.x endgültig einzustellen und alle Verfügbare Zeit des Teams und seiner Helfer auf MetaModels 2.0 zu stürzen. Ein Update von den alten Versionen auf MetaModels 2.0 wird möglich sein.

## MetaModels 2.1

Mit der 2.1.0 möchten wir uns dann bei gleichem Funktionsumfang um die Benutzerfreundlichkeit kümmern und schauen, wie wir einzelne Funktionen besser und verständlicher machen.

## Neue Features

Neue Features werden wir leider, unter anderem aufgrund des sehr mageren Spendenaufkommens (236 € – in den letzen 6 Monaten bei über 200 Stunden Arbeit... mehr ist leider echt nicht drin), frühestens im nächsten Jahr oder eben wie bisher durch Auftragsarbeiten angehen können.

**Comment by tim-bec** [comment]
@cboelter für die Conditions auf Legenden gibts noch nichts. Und das Sammelticket brauchen wir ;-)

**Comment by discordier** [comment]
@cboelter Nein, da gibt es noch nichts angefangenes.
Problematisch ist jedoch allgemein, dass dies wohl im DCG noch nicht supported wird. Du musst also alle properties einer Legende "hiden", dann wird die Legende automatisch verschwinden.
Ebenso werden die states der legends noch nicht gespeichert, sie sind also immer aufgeklappt.

**Comment by tim-bec** [comment]
Sammelticket Filter: https://github.com/MetaModels/core/issues/698

**Comment by xantippe** [comment]
Hallo Tim,

wie ist der aktuelle Stand von MM 2.0....??

Gruss

**Comment by psren** [comment]
Gute Frage. Kann man das mit irgendeiner Contao-Version im Moment halbwegs vernünftig nutzen und eventuell aufgeschobene Projekte schon starten?

**Comment by tim-bec** [comment]
@xantippe @psren - wir nutzen den aktuellen TNG sehr stabil mit Contao 3.2 + 3.3 - 

dank @cboelter und @discordier haben wir einige neue nette Features drin und einen ziemlich stabilen core. Ich geb aber zeitnah noch mal eine Zusammenfassung zu den Punkten der Roadmap.

**Comment by cboelter** [comment]
Ich nutze es mittlerweile relativ problemlos mit der 3.2LTS wobei ich in der letzten Zeit einiges an Fehlern und Fehlerchen beseitigt habe. Das Problem ist nach wie vor halt die Manpower, gerade aktuell sind da viele umständliche Dinge wie zum Beispiel die Factories etc. die einfach Zeit brauchen bis diese komplett nachgezogen sind.

**Comment by cboelter** [comment]
Ich glaube generell wäre es ein gutes vorgehen, wenn Ihr anfangt Projekte umzusetzen als zu warten das es die stabile 2.0 gibt.
Je mehr es testen um so mehr Fehler werden vor dem Release gefunden und beseitigt.

**Comment by xantippe** [comment]
Ich habe ein (neues) Testprojekt mit dem TNG vom 08.01.2015 - die "Grundfunktionen" wie MM und Attribute anlegen geht.
Jedoch Sachen wie Sortierung funktionieren nicht - ist in obiger Liste auch nicht abgehakt. Damit brauch ich das sicher nicht noch-noch-nochmal melden...

**Comment by Messa1** [comment]
Für mich auch die Sortierung wichtig. :+1:  Aber ich kann warten zur Not bastle ich selber etwas zusammen :) Ich glaube, dass eh viele Leute testen.

**Comment by cboelter** [comment]
Was genau funktioniert denn bei der Sortierung nicht? Bei mir tut sie das ohne probleme ...

**Comment by xantippe** [comment]
es geht um das BE
also bei mit (TNG 08.01. + C 3.3.7) erscheint in der Listenansicht bei "Sortierung" die Auswahl "Sorting" und "Information 2" - nach was und wie sortiert wird, eschließt sich mir nicht....

**Comment by discordier** [comment]
Dann schau mal in deine Sortierungs und Gruppierungsdefinitionen.
Das ist das neue icon in den Eingabemasken (das vorletzte).

**Comment by xantippe** [comment]
hmmm??
bin in "MetaModels > Alle Eingabemasken für "Speisen"

![01](https://cloud.githubusercontent.com/assets/1045318/5902969/2470db0c-a57f-11e4-8f6a-148293a47e53.jpg)

und dann in den Eigenschaften von "Name"

![02](https://cloud.githubusercontent.com/assets/1045318/5902976/32be059a-a57f-11e4-887d-f80ff1b36197.jpg)

Welches Icon?

**Comment by discordier** [comment]
Das hier: 
![image](https://cloud.githubusercontent.com/assets/940331/5903529/77aa1524-a582-11e4-8cb9-5044dc57345d.png)

**Comment by tim-bec** [comment]
@Messa1  - nein es testen definitiv nicht genug leute, bzw. wir können ja nur "unsere" use cases testen. Wir sind wirklich auf mehr tester und Fehlerreports & Nachfragen angewiesen!

Und wir freuen uns sehr über eure Mithilfe hier: http://metamodels.readthedocs.org/en/latest/manual/first-metamodel.html#input-screens

**Comment by xantippe** [comment]
Thema Manual - gibts das auch in "german"?

**Comment by xantippe** [comment]
Zum Sortieren: nach Update auf TNG von "heute" (26.01.2015) funktioniert die Sortierung - zumindest ist nun das Icon da :-)

**Comment by tim-bec** [comment]
@xantippe - aktuell wie du siehst noch nicht. Übersetzungen sind gerne gesehen ;-)

**Comment by xantippe** [comment]
habe mich bei Transifex für MM "gemeldet"...

**Comment by discordier** [comment]
Die docs sind noch nicht bei transifex. Werde ich aber baldmoeglichst aktivieren.

**Comment by xantippe** [comment]
dann kann ich ja ggf. was anderes übersetzen... ;-)

**Comment by cboelter** [comment]
@discordier @tim-bec evtl. wäre es ganz sinnvoll zu den docs ein Post in der Community zu machen. Mit dem Hinweis das Unterstützer gesucht werden.

**Comment by psren** [comment]
@cboelter Danke für die Infos :+1: . Dann teste ich auch mal :-)

**Comment by psren** [comment]
Mhhh, gibt es hier schon vom Timing her was neues?
Ich habe fleißig getesten und Tickets geschrieben, so richtig stabil wirkt das noch nicht (tng branch)

**Comment by cboelter** [comment]
Ich glaube das Problem am Timing ist aktuell nach wie vor die ManPower, was man ja durchaus an den Commits sieht. So lange das nicht auf einer soliden Basis steht, wird es wohl mit einem verbindlichen Timing schwer :(

**Comment by xantippe** [comment]
@tim-bec: Hallo Tim, wie aktuell ist die obere Liste? pflegst Du die noch..??

Gruss & Dank!

**Comment by Messa1** [comment]
Gibt es schon etwas neues? Wirk wie eingeschlafen? :) Bei den Factories Filters https://github.com/MetaModels/core/issues/698 wurde seit Jänner nichts mehr eingetragen.
Möchte wie immer keinen Druck machen aber ein paar Infos zum momentanen Stand wären schön :+1:

**Comment by tim-bec** [comment]
Sorry für meine lange Abwesenheit. Ich war beruflich so stark in anderen Projekten ohne MetaModels eingebunden das das Projekt bei mir ruhen musste.
Wir haben nun wieder mehrere neue Projekte mit MetaModels laufen und ich bin wieder aktiv mit dabei.

Kurz zur Lage der Nation:
- Ich habe in der letzten Woche drei MetaModels Installationen auf 3.4.4 mit TNG und DCG DEV-Develop erstellt und fahre bei allen aktuell ohne ein einziges Problem (nutze aber weder Variante noch Tree-Views) das nur so als hinweis, wie stabil MM aktuell ist.
- Wir haben die Tickets noch mal ein wenig aufgeräumt, auch wenn die 2.0 Todo noch einige offene Punkte hat ist das bis auf 4-5 Tickets eher Peace-of-Cake
- Wir nehmen uns dem ganzen nach wie vor nach und nach an, aber wie immer: Die Fehler die uns in eigenen Projekten auffallen sind natürlich schneller behoben als Tickets hier.
- Wem ein Fehler Massiv auf die Füße fällt kann @discordier mit der Behebung beauftragen

Vielen Dank hier auch noch an @cboelter für das viele Bugfixing. 

Bis in zwei Wochen dann,
Tim

**Comment by psren** [comment]
Mit der Contao 3.2.x habe ich eine Installation mit den Varianten am laufen und soweit läuft das alles ganz gut.
Baum kann ich allerdings nichts sagen.
Was insgesamt gesagt werden muss ist dass von Dezember bis jetzt extrem viel passiert ist
und sich Metamodels inzwischen ziemlich stabil einsetzen lässt.
:+1:  * :100: 
Lob :-D

**Comment by xantippe** [comment]
"... lebt denn der alte Holzmichel noch...?... jaaa er lebt noch!" ;-)

Dank für das Lebenszeichen!

**Comment by Messa1** [comment]
Wie sieht es mit einem Update aus? Wie weit seit ihr?

**Comment by tim-bec** [comment]
Ein Lebenszeichen:

@netzmacht arbeitet seit dieser Woche mit an MetaModels und hat schon einige Bugs beseitigt und lang vermisste Features ( copy & paste!) implementiert. Da das ganze im DCG und MetaModels hängt wird das zusammenfügen noch etwas dauern. Nach dem ausmerzen steht noch die große Runde Version-Tagging und Branch renaming an. Dann haben wir aber eine 2.x - bleibt neugierig :-)

**Comment by xantippe** [comment]
Wow! ick freu mir...

**Comment by pagestyles** [comment]
made my day!

**Comment by discordier** [comment]
@xantippe MM 2.X ist bislang nur bis 3.4 freigegeben, du kannst aber gerne einen nightly in eine 3.5 ziehen und Bugs reporten. Geplant ist es, dass wir uns fyr 3.5 oeffnen, aber bis wir alle dependencies soweit haben, das schleicht.

Je mehr PRs usw. wir auch bei den CCA Projekten bekommen, desto schneller geht es.

**Comment by xantippe** [comment]
o.k. - wollte nur mal wissen, ob 3.5 in Planung oder aussen vor...

**Comment by tim-bec** [comment]
@xantippe wir haben alle attribute, filter und den core auf contao/core <3.6 hochgezogen. Ein installieren über composer geht nun auch wieder und nach unseren bisherigen tests läuft auch alles. \o/

**Comment by MacKP** [comment]
+1 ich glaub ne News dazu wäre gut ;-)

**Comment by xantippe** [comment]
+1 dito!

**Comment by xantippe** [comment]
Wir nähern uns dem Einjährigen des Postings ;-)

**Comment by Teetrinker** [comment]
@tim-bec Ich wäre interessiert an einem Zwischenstand. Wie siehts aus, wo steht ihr?

**Comment by xantippe** [comment]
am kommenden Dienstag (20.10.15) "sitzen" wir bei Mumble zusammen um den "Stand der Dinge" und die weiteren Aufgaben duchzusprechen - Fokus liegt hierbei eher auf Themen wie Kommunikation, MM-Webseite, News, Handbuch, usw.

anschließend wird es sicher genauere Infos geben

**Comment by xantippe** [comment]
@all: eine Zusammenfassung des Calls ist auf der MM-Webseite unter Aktuelles zu finden...
https://now.metamodel.me/de/aktuelles/details/endlich

**Comment by xantippe** [comment]
@all: News https://now.metamodel.me/de/aktuelles/details/november-infos-2015

**Comment by xantippe** [comment]
@all: Neue Bezeichnungen und Icons für MetaModels
siehe http://metamodels.readthedocs.org/de/latest/manual/new-labels.html#manual-new-labels

**Comment by xantippe** [comment]
@all: News: https://now.metamodel.me/de/aktuelles/details/2015-dezember-infos

**Comment by xantippe** [comment]
@tim-bec kannst Du die aktuellen Bearbeitungen mit einpflegen - das Ticket ist immer noch eine gute Anlaufstelle..

**Comment by xantippe** [comment]
News: https://now.metamodel.me/de/aktuelles/details/2016-januar-infos

**Comment by xantippe** [comment]
News: https://now.metamodel.me/de/aktuelles/details/2016-februar-infos

**Comment by xantippe** [comment]
News: https://now.metamodel.me/de/aktuelles/details/2016-maerz-infos

**Comment by zonky2** [comment]
News: https://now.metamodel.me/de/aktuelles/details/2016-april-infos

**Comment by zonky2** [comment]
News: https://now.metamodel.me/de/aktuelles/details/2016-mai-infos

**Comment by zonky2** [comment]
News: https://now.metamodel.me/de/aktuelles/details/2016-juni-infos

**Comment by zonky2** [comment]
News: https://now.metamodel.me/de/aktuelles/details/2016-juli-infos
